app:
  url:
    base: http://localhost:8080
    password-reset-path: /api/v1/auth/reset-password

spring:
  jpa:
    hibernate:
      ddl-auto: update        # 운영 전환 시 validate 또는 none으로 바꾸기
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration: 1800000 # 30분 (30 * 60 * 1000)
  refresh-expiration: 604800000 # 7일 (7 * 24 * 60 * 60 * 1000)